KeepDoingSomething/Algorithm-Study

CJH/Week00/boj1158_요세푸스문제/Main.java
CJH/Week00/boj14501_퇴사/Main.java
CJH/Week00/boj2776_암기왕/Main.java
CJH/Week00/boj3986_좋은단어/Main.java

Java 문제풀이입니다.
요세푸스 문제는 풀어 본 경험이 있어, 큐를 활용하여 기억나는 풀이로 작성하였습니다.
암기왕은 hasmap, set, 배열 index(배열 생성 범위 문제로 실패)로 풀이 가능할 거 같은데, 자주 쓰는 hashmap으로 풀이하였습니다. 
좋은단어는 문제 이해가 잘 안됐지만, stack으로 푸니까 쉽게 가능하였습니다. 
퇴사 문제는 몰라서 유튜브 문제풀이 참고하여 백트래킹 풀이 작성하였고, DP 문제풀이는 학습 예정입니다.

[1주차 / 최지호] 문제풀이

---

허준범/BOJ/Week03/[LV 2]표 편집.java

PR 먼저 올립니다!
LV3_81303 표 편집 (X)
- 28점으로 풀이중입니다..
LV2_86971 전력망 둘로 나누기(X)
LV3_250135 아날로그 시계 (X)

[3주차 / 허준범] 문제풀이

---

CJH/Week02/아날로그시계/Solution.java
CJH/Week02/전력망을둘로나누기/Solution.java

금주는 2문제만 풀겠습니다. 
전력망을 둘로 나누기는 아이디어는 알겠는데, 구현방법을 몰라서 블로그 참고하였습니다. 
아날로그 시계는 어려워서 이런 문제도 있구나 하면서 블로그 보면서 학습하였습니다. 그렇게 해도 오래 걸리네요.

[3주차 / 최지호] 문제풀이

---

윤건수/BaekJoon.java
윤건수/Problem.java
윤건수/Programmers.java
윤건수/TestMain.java
윤건수/programmers/LV2_250135/Solution.java
윤건수/programmers/LV2_250135/TestCase.java
윤건수/programmers/LV2_86971/Solution.java
윤건수/programmers/LV2_86971/TestCase.java
윤건수/programmers/LV3_81303/Solution.java
윤건수/programmers/LV3_81303/TestCase.java

- [PASS] 전력망을 둘로 나누기  (Level 2)
BFS 이용하여 풀었습니다. 조건이 딱 두 구간으로 나누어 지는 형태여서 끊어진 지점 중 한 곳을 탐색 후 결과를 냈습니다.
- [PASS] [PCCP 기출문제] 3번 / 아날로그 시계  (Level 2)
초 단위로 각 초침, 시침, 분침의 각도 변화를 계산하여 교차 되었는지 체크하여 풀었습니다.
시분초침이 동시에 겹치는 조건이 잘 모르겠어서 좀 찾아보게 되었는데 그냥 단순히 12시 한 경우밖에 없더군요 ...
-  [PASS] 표 편집  (Level 3)
처음에 생각했던 건 Java LinkedList 컬렉션 이용하려 했는데 되돌리기 명령 관련해서 구현이 어려울 것 같기도하고, 어떻게 구현해도 효율성이 떨어질 것 같아서 
다음으로 표 배열을 두고 인덱스 이동하는 형태로 시도했습니다만...
정확성 테스트에서 인덱스 범위 벗어나는 문제인지 왜 인지 모르겠는데 몇몇 케이스 오답과 런타임 에러가 발생... ㅠㅠ
효율성 테스트도 10가지 케이스 중 5가지 케이스 시간 초과나서 결국 포기하고, 찾아보다가 
최종적으로 LinkedList 개념으로 next와 prev를 field로 가지는 클래스를 직접 정의해서 풀으신 분들이 있는 것 같아서 해당 개념으로 풀어 보았고, 통과되었습니다

[3주차 / 윤건수] 문제풀이

---

전유진/BOJ/바이러스.java
전유진/BOJ/어린왕자.java
전유진/Programmers/소수찾기.java

[Pass] 소수 찾기
팩토리얼을 이용한 완전탐색 방법으로 풀었습니다.
[Pass] 바이러스
DFS로 풀었습니다.
[NO] 어린 왕자
구현으로 푸는 것을 예상하였으나, 풀지는 못하였습니다.

[4주차 / 전유진] 문제풀이

---

CJH/Week03/boj1004_어린왕자/Main.java
CJH/Week03/boj2606_바이러스/Main.java
CJH/Week03/소수찾기/Solution.java

소수찾기, 바이러스는 예전에 풀이보고 공부했던 문제라 금방 끝났고, 
어린왕자는 못 풀어서 참고 하였고,
윤건수님 코드에서 ^ XOR 연산 참고하였습니다. 
감사합니다.

[4주차 / 최지호] 문제풀이

---

허준범/BOJ/Week04/[2606] 바이러스.java

( O ) [2606] 바이러스
- BFS를 사용해서 풀었습니다
( X ) [1004] 어린왕자
- 풀이중입니다
( X ) [42839] 소수찾기 
- 풀이중입니다

[4주차 / 허준범] 문제풀이

---

KJH/Week04/boj1004_어린왕자/main.py
KJH/Week04/boj2606_바이러스/main.py
KJH/Week04/programmers_소수 찾기/main.py

Programmers 소수찾기
- 모듈 itertools의 순열 기능을 활용해서 풀었습니다.
- 모든 숫자 조합의 경우의 수를 만든 후, 소수가 아닐 경우 빼줬습니다.
팀프로젝트 일정상 이번주는 문제 풀이 수가 적습니다. ㅠㅠ

[4주차 / 김재환] 문제풀이

---

조은채/BOJ/G4_1922.java
조은채/Programmers/Lv2_12905.java

가장 큰 정사각형 찾기 [ O ]
DFS인 줄 알았으나 DP였던 문제였습니다.
DFS, DP 구분이 어렵네요,,!
네트워크 연결 [ O ]
최소 스패닝 트리에 대해 처음 공부해보고 Union & Find 형식으로 풀었습니다.
사칙 연산 [ X ]
아직 시도하지 못했습니다.

[5주차 / 조은채] 문제풀이

---

김호집/BOJ/java/Week06/1012.java
김호집/BOJ/java/Week06/1202.java
김호집/PROGRAMMERS/java/Week06/피로도.java

선 PR입니다.
블로그 작성이 완료되면 각각의 알고리즘 문제 하단에 문제 풀이 해설 blog 링크를 남기겠습니다.
---
**[Pass] LV2 피로도**
- 완전탐색으로 풀었습니다.
- 풀이 알고리즘은 DFS입니다.
---
**[Pass] 1012 유기농 배추**
- 그래프 탐색 문제입니다.
- DFS와 BFS 둘다 사용할 수 있는 문제로, stack overflow가 일어날 가능성이 있는 DFS보단 BFS를 더 선호하여 BFS로 풀었습니다.
**blog**
https://hohome-develop.tistory.com/1
---
**[Pass] 1202 보석도둑**
- 처음, 인자가 30만개까지 들어올 수 있는것을 보고, 최대 O(N*logN)으로 풀어야하는 점을 알았습니다.
- 이후, 보석 백팩 둘다 sort하여 완전탐색을 할 까 고민하다, heap을 활용하는 문제임을 인지하고, 그에 맞게 풀이를 하였습니다.

[6주차 | 김호집] 문제풀이

---

KJH/Week06/2_Boj1012_유기농배추.py

- 피로도
😓
- 유기농배추
DFS를 사용하여 풀었습니다!
- 보석도둑
😓

[6주차 / 김재환] 문제풀이

---

이인복/BOJ/java/com/Week07/G3_20058/마법사 상어와 파이어스톰.py
이인복/BOJ/java/com/Week07/G5_6593/상범 빌딩.py
이인복/BOJ/java/com/Week07/L2_1844/게임 맵 최단거리.py

- [Pass] 게임 맵 최단거리
> 기본 BFS 방식으로 풀었습니다.
- [Pass] 상범 빌딩
> 3차원 모양인 것 고려한 BFS 사용한 풀이 하였습니다.
- [Pass] 마법사 상어와 파이어스톰
> 문제는 풀었으나.... 더럽게 풀었고, Java 로 다시 풀지는 않을것 같습니다.
> Python3 로 돌리면 시간초과가 발생해서 다시 풀기 싫은 마음에 Pypy3 로 통과시켰습니다.
> 개인적으로 독해력이 낮아서 그런지 몰라도 문제를 이해하는데 시간의 절반은 사용 했습니다.
> 문제의 기능을 나누어서 접근 했습니다.
> 1. rotate (회전)
> - 정말로 많이 식을 지웠다 만들었습니다. (A4 용지도 거의 2장은 사용 했네요.)
> 2. melt (얼음 녹이기)
> - 얼음이 한 번에 같이 녹아야만 문제를 진행할 수 있어서 구현 하였습니다.
> 3. graph search (BFS)
> - 최대 값과 총 합을 구해주기 위해서 그래프 탐색을 이용 하였습니다.

[7주차 / 이인복] 문제풀이

---

CJH/Week07/boj6198_옥상정원꾸미기/Main.java
CJH/Week07/하노이의탑/Solution.java

- 하노이의 탑
풀이 참조
- 옥상 정원 꾸미기
풀이 참조
- 마법사 상어와 파이어스톰 
pass

[8주차 / 최지호 ] 문제풀이

---

이인복/BOJ/java/com/Week09/G4_9935/문자열 폭발.py
이인복/BOJ/java/com/Week09/LV2_77485/행렬 테두리 회전하기.py

- [Pass] 문자열 폭발
> 스택을 이용해서 크게 문제 없이 풀이 하였습니다.
- [Pass] 행렬 테두리 회전하기
> python 에서 deepcopy 를 사용해서 원본 배열을 보존 했는데 시간초과가 발생 했습니다.
> 확인 해보니 다른 분들도 같은 문제를 겪으셨는데 copy() 함수를 사용했을 때에는 통과 되었습니다.
- [Skip] 택배 배달과 수거하기
> 풀이 참조 했는데, 제가 수준 이상인거 같아서 패스 했습니다. (아이디어 싸움인거 같은데 현타오네요..ㅎ)

[9주차 / 이인복] 문제풀이

---

이인복/BOJ/java/com/Week09/LV2_150369/LV2_Q150369.java
이인복/BOJ/java/com/Week10/LV2_17677/LV2_Q17677.java
이인복/BOJ/java/com/Week10/LV2_42587/LV2_Q42587.java
이인복/BOJ/java/com/Week10/LV3_43164/LV3_Q43164.java

- [Pass] 택배 배달과 수거하기
> 문제를 이해하고, 해결하기 위한 설계를 하는 과정이 저는 개인적으로 힘들었습니다.
> 해설을 보면서 풀었고, 제가 문제 이해가 힘들었던 이유는 너무 시뮬레이션에 가깝게 풀이하려고 해서 였던것 같네요.
> 게임 하듯이 물건을 배달 & 수거가 이루어져야 한다고 생각해서 더 어려웠습니다.
- [Pass] 프로세스
> 다양한 자료구조를 사용해서 풀이를 시도할 수 있는 괜찮은 문제인거 같습니다.
> 저는 우선순위 큐 & 큐 를 사용해서 풀이했습니다.
- [Pass] 1차 뉴스 클러스터링
> 해쉬를 이용해서 문제를 풀이 하였습니다.
> 정규식은 GPT 의 도움을 받았고, 문자만 다뤄 준다면 크게 문제는 없을 것 같습니다.
> 다른 풀이들 참조해보니 다양한 자료구조와 풀이 방법이 보여서 좋은 문제인 것 같습니다.
- [Pass] 여행 경로
> 문제를 제대로 이해하지 못해서 방문 처리, BFS 로 시도 하면서 삽질을 조금 했습니다.
> 백트래킹 기법이나 완전탐색으로 풀이 하는게 저는 이상적이라 생각해서 해당 풀이 방법을 사용했습니다.

[10주차 / 이인복] 문제풀이

---

윤건수/TestMain.java
윤건수/programmers/LV2_17677/Solution.java
윤건수/programmers/LV2_17677/TestCase.java
윤건수/programmers/LV2_42587/Solution.java
윤건수/programmers/LV2_42587/TestCase.java
윤건수/programmers/LV2_43164/Solution.java
윤건수/programmers/LV2_43164/TestCase.java

- 프로세스 (Level 2) [O]
우선순위 큐를 이용하여 해결하였습니다.
- 뉴스 클러스터링 (Level 2) [O]
지문이 어려운 문제 같네요. 맵을 이용하였습니다.
- 여행경로 (Level 3) [O]
백트래킹 이용하여 풀이하였습니다.

[10주차 / 윤건수] 문제풀이

---

CJH/Week10/뉴스클러스터링/Solution.java
CJH/Week10/여행경로/Solution.java
CJH/Week10/프로세스/Solution.java

-  프로세스
우선순위 사용한다는 거 알고도 못 풀어 풀이 참조
- 뉴스 클러스터링
교집합 합집합 구하는 부분에서 잘 안되서 chatgpt 도움 얻어서 투포인터 풀이 학습
- 여행 경로
dfs로 풀려고는 했는데, 재귀 종료조건도 몰랐고, 방문처리도 어떻게 해야할지 몰라서
안 풀려서 풀이 참조하여 학습

[10주차 / 최지호] 문제풀이

---

이인복/BOJ/java/com/Week11/LV2_42860/LV2_42860.java
이인복/BOJ/java/com/Week11/LV2_42885/LV2_42885.java
이인복/BOJ/java/com/Week11/S2_1927/S2_1927.java

- [Pass] 조이스틱
> 많이 지저분하게 풀었고, 솔직히 다시 풀고 싶지 않습니다...
> 전략은 A 와 알파벳 거리와 이동 거리를 분리해서 바라보았습니다.
- [Pass] 구명보트
> 백준의 두 용액 문제가 생각나는 문제였습니다.
> 투 포인터 개념으로 풀었는데, 그 이유는 배열을 정렬 했을 때 limit 가장 큰 수가 먼저 걸리는지 확인할 수 있어서 였습니다.
- [Pass] 최소힙
> 문제를 선정한 이유는 내부 트리까지의 구현을 생각 했으나 너무나 힘든 과정이 될 것 같아서 제공해주는 클래스 이용 했습니다...ㅎ

[11주차 / 이인복] 문제풀이

---

CJH/Week11/boj1927_최소힙/Main.java
CJH/Week11/구명보트/Solution.java
CJH/Week11/조이스틱/Solution.java

- 최소힙 (Silver 2)
- 우선순위 큐 기본문제
- 구명보트 (Level 2)
간단한 그리디도 어렵네요. 그리디 문제 많이 풀어봐야겠습니다.
- 조이스틱 (Level 2)
어려워서 학습했습니다.

[11주차 / 최지호] 문제풀이 

---

김호집/PROGRAMMERS/java/Week12/멀쩡한사각형.java
김호집/PROGRAMMERS/java/Week12/연속부분수열합의개수.java
김호집/PROGRAMMERS/java/Week12/큰수만들기.java

[Pass] 연속 부분 수열 합의 개수
Greedy문제였습니다.
Set을 사용한 풀이들이 많은 것 같은데, Array로 나올 수 있는 결과값을 index의 형태로 보관하도록 하였습니다.
Set을 활용한 문제와 시간복잡도는 동일할것으로 생각하고있습니다.
[Pass] 큰 수 만들기
어떻게 통과가 되었는지는 모르겠는 문제입니다.
제 풀이를 보면, input number에 "9" * 50만, "0" * 50만 만큼의 String값을 넣어주고(즉, 9999~~9999900000~~~00000), k를 50만을 넣는다면 500,000 * 500,000 => O(N^2)라는 시간복잡도가 나오는것 같은데, 어떻게 통과가 된것인지 의문이네요...
[Pass] 멀쩡한 사각형
수학적 사고력이 필요한 문제였습니다.
패턴을 찾는 풀이를 보고 이해하였습니다.

[12주차 / 김호집] 알고리즘 스터디

---

윤건수/TestMain.java
윤건수/programmers/LV2_131701/Solution.java
윤건수/programmers/LV2_131701/TestCase.java
윤건수/programmers/LV2_42883/Solution.java
윤건수/programmers/LV2_42883/TestCase.java
윤건수/programmers/LV2_62048/Solution.java
윤건수/programmers/LV2_62048/TestCase.java

- [PASS} 큰 수 만들기 (Level 2)
스택을 이용하여 해결하였습니다.
- [PASS} 연속 부분 수열 합의 개수 (Level 2)
Set 을 이용하여 해결하였습니다.
- [PASS} 멀쩡한 사격형 (Level 2)
주어진 직선을 기준으로 위, 아래, 겹치는 경우에 따라 점이 이동하는 것을 이용하였습니다

[12주차 / 윤건수] 문제풀이

---

이인복/BOJ/java/com/Week13/G4_1753.java
이인복/BOJ/java/com/Week13/G5_1052.java
이인복/BOJ/java/com/Week13/LV2_250136.java

- [Pass] 최단경로
> 다익스트라 문제 정말 많이 풀어서 익숙해진줄 알았는데 오랜만에 푸니까 헷갈리네요.
> 개념은 알고 있어서 풀다 보니까 풀렸습니다.
> 다익스트라 기본 문제여서 그래프 탐색 로직을 제외하고 특별한건 없네요.
- [Pass] [PCCP 기출문제] 2번 / 석유 시추
> 효율성 때문에 문제를 풀기 전에 설계를 고민하고 풀었습니다.
> column 단위로 탐색은 진행하지만, 석유 지역을 만나면 그래프 탐색 이후 y축이 일치하는 지역들에 탐색으로 확인한 지역의 크기를 더해주는 방식으로 진행 했습니다.
- [Pass] 물병
> 그리디 문제라고는 생각 했지만 감이 안잡혀서 참고해서 풀었습니다.
> 비트마스킹 풀이도 있었지만 제가 처음 구상한 풀이랑 가장 유사한 풀이로 선택 했습니다.
> 물이 합쳐지기 위한 조건 2의 지수승을 이용한 풀이와 유사하게 나눠서 남는 물병의 개수를 계산 하면서 N 의 값을 1승 증가시켜서 K 조건에 만족할 때 까지 반복하는 풀이 입니다.

[13주차 / 이인복] 문제풀이

---

전유진/BOJ/물병.java
전유진/BOJ/최단경로.java

[pass]최단경로 (Gold 4)
다익스트라 알고리즘으로 문제 해결하였습니다.
물병 (Gold 5)
그리디 알고리즘이라는 것을 이해 했으나, 풀지 못하여 코드 참고하였습니다...
석유 시추 (Level 2)-x

[13주차 / 전유진 ] 문제 풀이

---

이인복/BOJ/java/com/Week14/LV2_17686.java
이인복/BOJ/java/com/Week14/LV2_176962.java
이인복/BOJ/java/com/Week14/S1_9081.java

이번 주 프로그래머스 문제 풀이는 최대한 객체 지향적으로 풀어보려고 노력 했습니다.
별 다른 이유는 없이 이렇게도 풀 수 있지 않을까 하는 마음으로 풀어봤는데, 코드로만 설명하기에는 무리가 있어서 '과제 진행하기' 문제는 따로 정리해서 올립니다.
- [Pass] [3차] 파일명 정렬
> 파일을 헤더, 바디, 푸터 3개를 나눌 때 각 요소들을 객체라고 생각하고 풀이 하였습니다.
알고리즘 문제만 생각하면 새로운 인스턴스를 생성하기 보다는 String 타입으로 Body 라던지 Header 를 저장하면 더 효율적인 결과가 나올 것 같지만, 제 생각대로 구현하는게 우선이라서 이런 풀이가 나왔습니다.
- [Pass] 과제 진행하기
[과제 진행하기](https://nashs789.tistory.com/149)
> 자바에서 시간을 다루는 time package 를 적극저으로 이용해서 문제를 풀이 하였습니다.
주석도 많이 달았지만 시각화 해서 정리한 글을 같이 첨부합니다.
- [Fail] 단어 맞추기
풀이 하고 있습니다. (메모리 초과 발생으로 조합을 만드는 코드를 수정할 예정입니다.)

[14주차 / 이인복] 문제풀이

---

CJH/Week14/boj9081_단어맞추기/Main.java
CJH/Week14/과제진행하기/Solution.java
CJH/Week14/파일명정렬/Solution.java

* [fail] 과제 진행하기 
- 조건 설정을 잘 못해서 chatgpt 도움 받았습니다. 
* [fail] 단어 맞추기
- 다음순열(next permutation) 을 공부해야겠습니다. 
* [pass] 파일명 정렬
- 그나마 풀만한 정렬문제지만 오래 걸려서 풀이.. 문제를 잘 읽어야함

[14주차 / 최지호 ] 문제 풀이

---

전유진/Programmers/과제_진행하기.java
전유진/Programmers/파일명_정렬.java

[fail] 과제 진행하기
우선순위 큐를 이용해서 몇시간 동안 풀어봤지만, 테스트코드 1만 맞고 나머지는 틀렸습니다 !.. 나중에 다시 한번 풀어보도록 하겠습니다 ! 
[x] 단어 맞추기
[pass] 파일명 정렬
head, number, tail 분리해서 새로운 클래스인 Files에 삽입하여 정렬하여 문제 해결했습니다 .
다른 블로그 참고하긴 했지만, 정렬을 이용해서 풀었습니다 :) 
이번에 정렬에 대해 다시 학습할 수 있었던 시간이였습니다 ! 👍

[14주차 / 전유진 ] 문제풀이

---

이인복/BOJ/java/com/Week14/LV2_17686.java
이인복/BOJ/java/com/Week14/LV2_176962.java
이인복/BOJ/java/com/Week14/S1_9081.java
이인복/BOJ/java/com/Week15/LV2_118667.java
이인복/BOJ/java/com/Week15/LV2_172927.java

기둥과 보 설치 문제는 읽기만 했는데 푸는데 시간 좀 걸릴거 같아서 다른 문제 두 개 우선 PR 올립니다.
- [Pass] 광물 캐기
> 그리디 문제로 정렬 -> 가장 큰 값을 가져올 수 있는 시나라오로 코드를 구성 했습니다.
> 8번 케이스만 통과하지 못했는데, 질문 게시판에 8번 케이스에 대한 설명이 있어서 찾아서 해결 했습니다.
- [Pass] 두 큐 합 같게 만들기
> 단순하게 두 큐의 값을 옮기면서 풀이 했습니다.
> 1번 케이스만 통과하지 못해서 마찬가지로 질문 게시판에 도움을 받았습니다.
> 보니까 다른 알고리즘으로 푸신분들도 계시는데  직관적으로 바로 생각이 안나서 신기하네요.
- [Fail] 기둥과 보 설치
> 아직 문제를 읽는 단계 입니다. (힘들거 같다는 직감이 드네요. 아마도...?)

[15주차 / 이인복] 문제풀이

---

CJH/Week15/광물캐기/Solution.java
CJH/Week15/두큐합같게만들기/Solution.java

[fail] 광물 캐기
풀이 보고 겨우 이해 중.. 
[Pass] 두 큐 합 같게 만들기
그나마 제일 간단.. 
[Fail] 기둥과 보 설치
문제 이해가 안됨 ㅎㅎ

[15주차 / 최지호] 문제풀이

---

이인복/BOJ/java/com/Week15/LV2_172927.java
이인복/BOJ/java/com/Week16/LV2_42583.java
이인복/BOJ/java/com/Week16/LV2_68936.java
이인복/BOJ/java/com/Week16/LV3_43162.java

주말까지 시간이 안날 것 같아서 풀이한 문제 먼저 올리겠습니다.
> 주어진 트럭 리스트를 그대로 사용 하려다고 용이하게 풀기 위해서 Queue 로 옮겨 담아서 풀이 했습니다.
Bridge 에 다리에 관한 정보를, Truck 에 각 트럭 정보를 담고 시간을 1초씩 증가 시키면서 순차적으로 조건들을 풀이 했습니다.
> DFS 로 풀이 했으며 주어진 배열을 그래프로 그대로 이용해서 풀었습니다.
사실 문제를 처음 접했을 때 유니온 파인드 문제라고 생각 했는데, 제가 잘 사용할줄 몰라서 그래프 탐색으로 풀이 했습니다.
> 분할 정복이라 생각하고 문제 풀이 했습니다.
매번 사분면을 나눌 때 마다 0 혹은 1인지 확인하고, 같은 수로 이루어져 있을 때만 카운팅 진행 했습니다.

[ 16주자 / 이인복] 문제풀이

---

박정민/week16/programmers_네트워크.java
박정민/week16/programmers_다리를지나는트럭.java
박정민/week16/programmers_쿼드트리후압축하기.java

16주차
네트워크 (Level 3)
bfs 로 풀이했습니다.
쿼드 압축 후 세기(Level 2)
백트래킹으로 한 사각형을 4개로 계속 쪼개나가는 식으로 풀었습니다.
다리를 지나는 트럭 (Level 2)
큐를 이용해 풀었습니다.
다리를 배열로 만들어서 한칸씩 뒤로 떙겨주는 부분이 좀 비효율적인거같습니다.
while(큐가 비어있을때까지)
1초 증가 
다리 한칸씩 뒤로 땡겨주기
새로운 트럭 올릴수있으면 올리기

[ 16주자 / 박정민] 문제풀이

---

CJH/Week16/기둥과_보_설치/Solution.java
CJH/Week16/네트워크/Solution.java
CJH/Week16/다리를지나는트럭/Solution.java
CJH/Week16/쿼드압축후개수세기/Solution.java

> 처음에 배열을 리스트로 변환해서 풀었다가, 배열 풀이로 변경 
> 백준 색종이 만들기 문제 풀고 와서 풀었음.  같은 문제
> 못 풀어서 풀이 참고하여 학습

[ 16주자 / 최지호] 문제풀이

---

이인복/BOJ/java/com/Week17/LV2_155651.java
이인복/BOJ/java/com/Week17/LV2_169199.java
이인복/BOJ/java/com/Week17/LV2_42746.java

> 일반적은 BFS 로직을 변형하여 풀이 하였습니다.
> 다만 주어진 String[] 구조를 제 입맛에 맞게 변경해서 풀이 했는데, 성능만 생각하는 코딩 테스트에서는 어떻게 볼지는 모르겠네요.
>
> 방문 체크를 할 때 방향도 움직인 방향도 같이 표시하기 위해서 3 차원 배열을 사용 했습니다.
> 이런 유형의 문제는 LocalTime 으로 풀기 힘드네요... 또 LocalDateTime 으로 변경해서 풀었습니다.
풀다가 느끼는 거지만 전에 건수님이 풀이한 형태로 시간을 변경해서 푸는게 더 용이할 거 같아서 남는 시간에 다른 풀이로 풀어볼 것 같네요.
>
> 정렬과 큐 를 적극적으로 이용해서 풀었습니다.
> 예전에 풀어봤던 문제 였는데, 기억이 안나서 이전 풀이 참고 했습니다.
다만 코드가 짧고, 아이디어 문제여서 스포일러 될까봐 이 곳에는 적지 않겠습니다.

[ 17주자 / 이인복] 문제풀이

---

강산아/programmers/week14/과제진행하기.java
강산아/programmers/week14/파일명정렬.java
강산아/programmers/week17/가장큰수.java
강산아/programmers/week17/리코쳇로봇.java
강산아/programmers/week17/호텔대실.java

:sparkles: Week17 강산아 문제풀이
- [v] <b>호텔 대실</b>
> 풀면서 재밌었습니다. PQUEUE 헷갈려서 찾아보며 풀었습니다
- [v] <b>가장 큰 수</b>
> 조건에 맞춰 정렬만 잘 하면 되는 문제..
- [v] <b>리코쳇 로봇</b>
> 전형적인 BFS에 조건 추가인걸 알았으면서...도 연습이 안되어있으니 어려운 것 같네요
> 이리저리 헐 것에 치이다 오랜만에 ps 다시 하니까 재밌으면서 어렵습니다 다시 열심히 달리겠습니다(self 다짐)

[17주차/강산아] 문제풀이

---

CJH/Week17/가장큰수/Solution.java
CJH/Week17/리코쳇로봇/Solution.java

> 문제 제대로 안 읽고 한칸씩 이동하여 거리 체크로 했는데 벽이나 장애물에 부딪히면 멈추는 조건은 구현 못해서 chatgpt 참고함.
> 생각보다 보다 쉬울거 같은데 못 풀어서 예전 풀이 다시 보고 함 
> 여유 없어서 패스

[17주차 / 최지호] 문제풀이

---

윤건수/TestMain.java
윤건수/programmers/LV2_155651/Solution.java
윤건수/programmers/LV2_155651/TestCase.java
윤건수/programmers/LV2_169199/Solution.java
윤건수/programmers/LV2_169199/TestCase.java
윤건수/programmers/LV2_42746/Solution.java
윤건수/programmers/LV2_42746/TestCase.java

> 일반적인 좌표 이동 문제에 자잘한 조건들이 추가되서 푸는데 오래 걸린것 같습니다.
> 아이디어를 잘 떠올릴수 있다면 쉽게 풀 수 있는 문제였습니다.
> 시간 변화에 따른 구현 문제들이 꽤나 자주 나오는 것 같네요. 입실, 퇴실 시간 큐를 이용하여 풀었습니다.

[17주차 / 윤건수] 문제풀이

---

전유진/Programmers/가장큰수.java
전유진/Programmers/두_큐_합_같게_만들기.java
전유진/Programmers/호텔대실.java

> Pass
> 이전에 문제를 푼 경험이 있었습니다 !.
모든 배열의 값들을 String으로 변환하고 정렬을 이용해서 문제 해결.
> 큐 이용해서 풀어야할 것을 예상했지만, 결국 다 풀지는 못해서 다른 분거 참고해서 문제 해결

[17주차 / 전유진 ] 문제 풀이

---

김수미/boj/G5_1956.java
김수미/boj/G5_1956.py
김수미/boj/G5_9205.java
김수미/boj/G5_9205.py

[O] [맥주 마시면서 걸어가기] (python, java)
처음에는 수학적으로만 계산하여 풀었으나, 아래와 같은 문제점을 발견했습니다.
- 상근, 편의점1, 편의점2, 페스티벌의 위치가 순서대로 위치에 있을거라는 보장이 없다.
- 상근 - 페스티벌 위치가 편의점을 들리지않아도(맥주를 구매하지않아도) 갈 수 있다면, 편의점을 들리지 않아도 된다.
그래서 **모든 정점을 탐색**하여 가능한 경우가 있으면 happy를 출력하는 방식으로 변경하여 문제를 풀었고, 이 과정에서 BFS를 사용했습니다.
[O] [운동] (python, java)
문제를 풀다보면, 한 정점에서 시작해서 다른 정점으로 가는 최단거리가 아니라, **모든 가능한 정점 쌍의 최단거리**를 알 필요가 있을 때도 있습니다. 저는 항상 최단경로를 생각할 때, BFS 또는 다익스트라를 생각하는데, 이런 문제의 경우 폴로이드-워셜 알고리즘을 사용하는 것이 구현이 간단하기 때문에 사용하여 구현했습니다. 점화식은 아래와 같습니다.
모든 지점에서 다른 모든 지점까지의 최단거리를 저장해야하기 때문에 2차원 테이블에 최단 거리 정보를 저장합니다. 
[X] [방금 그 곡]
이번주는 이 문제는 못 풀었습니다 🥲

[18주차 / 김수미 ] 문제 풀이

---

이인복/BOJ/java/com/Week20/G5_13265.java
이인복/BOJ/java/com/Week20/LV2_12980.java
이인복/BOJ/java/com/Week20/LeetCode_5.java

> 그래프 탐색으로 문제 풀이 하였는데, 개념 자체는 이진 트리 개념이네요.
> 그래프가 한 개가 아닌 점을 고려하지 않아서 조금 감을 못 잡았었는데, 그 것 제외하면 편했습니다. 
> 문제 제목이 `색칠하기` 여서 그래프 노드를 색칠하면서 풀었습니다. ㅋㅋㅋ
> 문제를 처음 접했을 때 그래프 탐색 알고리즘을 사용해서 풀 수 있다고 생각하고 풀이 했는데 시간 초과가 발생 했습니다.
> 로직 자체는 컴팩트 하다고 생각해서 다른 사람들 풀이를 참조 했는데, 접근 방법이 잘 못 되었네요.
> 풀이 참조해서 풀었습니다.
> 풀고 싶은 풀이가 있어서 스터디 피드백 시간 이전 까지는 풀어 보겠습니다.
> DP 로 풀고 싶었는데, 자력으로 못 풀어서 다른 사람들 풀이를 참고해서 풀었습니다.
> 다른 사람들 풀이 이해하는데도 오래 걸렸네요 :(

[20주차 / 이인복 ] 문제 풀이

---

강산아/boj/week19/Z.java
강산아/boj/week20/색칠하기.java
강산아/leetcode/week20/LongestPalindromicSubstring.java
강산아/programmers/week19/혼자서하는틱택토.java
강산아/programmers/week19/후보키.java
강산아/programmers/week20/점프와순간이동.java

> 경우의 수를 고려하다 보니 너무 헷갈려서 구글링의 도움을 받았습니다 코드를 보면서 이해했습니다
> 단순 구현 문제라 어렵지 않게 풀 수 있었습니다.
> dfs를 활용하는 문제 같은데 아직 숙달이 덜 되어서 헤매고 있습니다..

Week20 강산아 문제풀이

---

강산아/boj/week23/RGB거리2.java
강산아/boj/week23/해킹.java
강산아/programmers/week23/숫자의표현.java

> 단순 구현 문제였습니다.
> 오랜만에 ps하니 감이 안오네요.. 다시 감 잡으면서 풀이 참고 후 풀었습니다
> 해킹 문제와 마찬가지로 풀이를 참고 하였습니다. 다음 주 부터는 ps 집중하여 풀 수 있을 것 같습니다. 열심히 하겠습니다

23주차 강산아 문제풀이

---

박정근/BOJ/Week23/[10282]해킹.java
박정근/BOJ/Week23/[17404]RGB거리_2.java
박정근/Programmers/Week23/숫자의_표현.java

> 첫 풀이에서는 3차원 DP로 풀이했고, 이후 최적화하여 2차원 DP로 풀이했습니다.  
> 첫 번째 집을 색 j로 칠했을 때, i번째 집을 칠할 때 색 k로 칠할 수 있는 경우의 수를 구하도록 하여, "첫 번째 집을 어떻게 칠했는지에 대한 상태"를 계속 가져가려고 했습니다. 최적화하기 위해 다시 곱씹으며 풀이해보니 고칠 점이 많더군요. 
> 1. 첫 번째 집을 어떻게 칠했는지에 대한 상태를 굳이 가져가면서 N+1 행까지 가는 것 보다는, 특정 색부터 시작해서 1번부터 N번째 집까지 칠한 경우의 수를 구한 뒤 1번과 N번 색이 다른 경우만 처리해주면 되었습니다.
> 2. 굳이 DP 배열을 -1로 설정하는 것 보다는, 초기값을 최댓값으로 설정한 뒤 경우의 수마다 Math.min 연산을 해주었습니다. 단순히 Integer.MAX_VALUE 를 사용하면 오버플로우가 발생할 수 있기에 적당히 큰 수를 빼주어 초기값으로 설정했습니다.
> 3. 처음엔 Scanner 를 사용했는데, BufferedReader 와 StringTokenizer 를 사용하니 성능이 확 좋아지더군요. ( 260ms -> 120ms / 20364 KB -> 14688 KB )
> 오랜만의 DP 문제라서 재밌었습니다.
> 첫 풀이에서는 누적 합 + 이분 탐색으로 풀이했고, 이후 최적화하여 수학으로 풀이했습니다.
> 특정 수를 연속한 자연수들의 합으로 표현하기 위해선, 1부터 i까지의 연속된 자연수의 합에서 1부터 j까지의 연속된 자연수의 합을 제하면 된다는 아이디어를 떠올려 시작했습니다. (n = S[1..i] - S[1..j])
> 1부터 …

[23주차 / 박정근] 문제 풀이

---

이성원/Backjoon/17404 RGB거리 2.java
이성원/Programmers/숫자의표현.java

> {단순 구현으로 풀었습니다}
> {문제를 풀때 다른 사람의 풀이를 참고하면서 진행했습니다.
DP는 점화식을 새우는게 가장 어려웠습니다. 모든 경우의 수를 다 봐야 했기 때문에 이차원 배열인 DP를 사용했습니다.
1.  첫번째 집에 색깔을 선정하고 선정이 안된 색깔은 무한대로 처리를 했습니다 -> 최솟값을 구하기 위해
2. 두번째 집부터 N까지 반복하여 집의 색깔을 선정하돼, 첫번째 집이랑 색깔이 겹치지 않도록 집을 선정하여 값을 저장해줬습니다.
3.  마지막 집에 최종 값이 이므로 최솟값을 구하돼 마지막 집이 첫번재 집과 색깔이 같은거는 제외 시켜줬습니다.}
> {아직 다익스트라는 고난도 알고리즘이여서 넘어갔습니다}

:sparkles: Week23 이성원 문제풀이

---

양문규/BOJ/Week23/17404.py
양문규/Programmers/Week23/12924.py

> DP 문제를 오랜만에 해서 챗 지피티의 도움을 받아서 해결했습니다. 최대한 코드가 아닌 아이디어를 도움 받아 스스로 해결할 수 있도록 노력했습니다. 오랜만에 풀어보니 좋았어요.
> 투 포인터라는 개념을 처음 알게 되었네요. 개념을 알면 상당히 쉬운데 모르면 해결책을 떠올리기가 쉽지 않겠단 생각이 들었어요. 좋은 공부가 되었습니다!
> 이 문제는 좀 어려워서 아직 못 풀었습니다. 다익스트라 기본 형태의 문제부터 차근히 풀어보고 다시 도전해볼 생각이에요~.

[23주차 / 양문규] 문제 풀이

---

이인복/BOJ/java/com/Week24/G4_1477/G4_1477.java
이인복/BOJ/java/com/Week24/LV2_131704/LV2_131704.java
이인복/BOJ/java/com/Week24/LV2_92342/LV2_92342.java

> 문제 읽으면서 풀이가 구상이 되었는데 백준 문제중에 공유기(?) 네트워크(?) 관련된 문제랑 상당히 유사한 문제 였습니다.
> 주어진 구간 사이에서 만들 수 있는 최소 값을 구하기 위해서 이분 탐색을 통해서 문제를 풀어 나갔습니다.
> 다만 풀이를 한 번 다 지우고 다시 풀었었는데
```
0   -   82   -   201  -  411  -  555  -  622  -  755  - 800
⎿  82  ⏌⎿ 119 ⏌ ⎿ 210 ⏌⎿ 144 ⏌⎿ 67 ⏌⎿ 133 ⏌⎿ 45 ⏌
```
> 위와 같이 구간 사이의 거리를 미리 산출하여 새로운 배열을 만들어서 풀이를 진행 했었고, N 이 0 이 주어져서
> 구간이 시작과 끝을 제외하고 안만들어 질 수 있다는 점을 배제하고 풀이 하여서 전부 지우고 다시 했습니다... (해당 케이스 떄문에 엄청 틀렸네요.)
> main 컨베이어는 주어진 배열을 그대로 이용 하였고, sub 컨베이어는 스택을 이용해서 자료 구조를 잡았습니다.
> main, sub 에 순서에 해당하는 상자가 없는 케이스를 종료 조건으로 잡았습니다.
> 문제 조건이 제 입장에서는 상당히 까다로워서 깔끔한 풀이는 만들지 못했고, 많은 주석으로 코드 설명을 대체했습니다. (정리할 엄두가..)
> 완전 탐색을 제외하고는 풀이 방법이 생각나지 않아서 백트래킹 기법을 이용해서 조합을 만들어냈습니다.
> - 화실이 남았는데 0 점에 도달할 때 화살을 전부 소모하는 것을 간과
> - 아파치와 라이언이 같은 점수를 얻은 케이스를 간과
> 
> 위 상황 말고도 많은 케이스들이 있었던 것 같은데 기억은 안나네요.

[24주차 / 이인복 ] 문제 풀이

---

박정근/BOJ/Week24/[1477]휴게소_세우기.java
박정근/Programmers/Week24/양궁대회.java
박정근/Programmers/Week24/택배상자.java

> 첫 풀이에서는 구현량이 많은 백트래킹으로 풀이했습니다.
> 그리디, DP 를 사용할 수 있는지 고민해보다가, 시간 복잡도가 가능해서 백트래킹으로 풀이했습니다.
> 특정 점수를 가져가는지 / 가져가지 않는지에 대한 백트래킹으로, 최대 O(2^11) 만큼 재귀함수를 호출했습니다.
> 거의 완전 탐색에 가까워서, 구현량도 많고 시간 소모도 컸습니다. (ArcheryComp 클래스를 만들어 구현했습니다.)
> 이후 최적화를 통해 비트마스킹 + 완전 탐색으로 풀이했습니다.
> 첫 풀이가 완전 탐색과 비슷하게 백트래킹을 진행한다는 특성을 이용해, 2^11 을 처음부터 끝까지 탐색하자는 아이디어를 얻었습니다. 
> 어피치가 점수를 가져간 상태를 0, 라이언이 점수를 가져간 상태를 1로 두고 비트 이론을 이용해 00000000001(2) 부터 11111111111(2) 까지 탐색했습니다.
> 시간이 3.63ms -> 1.67ms로 절반 가량 줄었습니다. 할 수 있다면 이후에 DP로도 풀이할 수 있을 것 같은데, 점화식이 잘 떠오르진 않네요.
> 완전 탐색으로 풀이했습니다.
> 처음에는 가장 긴 구간 사이 중간 지점에 휴게소를 설치하는 방법을 떠올렸으나, 최적의 방법이 아님을 알게 되었습니다.
> 0부터 100까지의 구간에 휴게소를 2개 설치한다고 가정하면, [33, 33, 34] 로 나누는게 최적이지만, 중간 지점 설치 아이디어는 [25, 25, 50] 구간이 만들어지기 때문입니다.
> 입력으로 들어온, 위치를 바꿀 수 없는 휴게소들은 그대로 두고, 최대 길이 구간을 최적으로 줄이는 방법을 떠올리고자 했습니다.
> 그 …

[24주차 / 박정근] 문제 풀이

---

양문규/BOJ/Week24/휴게소_세우기.py

> 이번에는 문제가 너무 어려워서 다른 두 문제는 손을 못댔습니다. ㅠ.ㅠ 지피티를 통해서 풀게 되었는데, 휴게소 간 간격을 고려를 못했습니다. 시작점과 끝점을 고려해서 그것까지 간격을 넣어야하는 걸 몰라서, 엄청 삽질 했네요. 첨엔 이게 왜 이분 탐색으로 푸는건지 이해하는 것조차 너무 오래걸렸습니다. 후. 답답하네요~~~ 담주에는 좀 더 발전된 모습으로 세 문제 도전해보겠습니다 ^^

[24주차 / 양문규] 문제 풀이

---

이상경/programmers/ArcheryCompetition.java
이상경/programmers/Delivery.java

> 전형적인 백트래킹 문제였고 몇개의 조건들이 추가로 있어서 조금 까다로웠지만 케이스별로 잘 나눠놓은 후에 풀이를 진행하면 더 좋았을 거 같네요. 남은 화살에 대한 처리 및 낮은 점수 많이 쏜 케이스를 고르는 부분만 잘 체크하면 되는 문제였습니다!
> 스택과 분기처리로 쉽게 풀 수 있는 문제였습니다.
> 흠.. 안풀다가 풀려니까 완탐, BFS, DFS, 구현 외에 알고리즘은 아이디어가 아예 안떠오르네요.. 요건 다른분들 풀이한거 보고 학습을 하겠습니다.
resolve #137

[24주차 / 이상경] 문제 풀이

---

강산아/boj/week24/휴게소세우기.java
강산아/programmers/week24/양궁대회.java
강산아/programmers/week24/택배상자.java

> 문제 이해가 어려웠습니다. 구간 별 분할하여 답을 구해내려 했으나 '구간'의 초점을 두기보다 '길이'의 초점을 두어서 풀어야 하는 문제였네요. 답안을 참고하며 문제 자체를 이해하려 노력했습니다.
- [] <b>양궁 대회</b>
> 아직 답을 풀지 못하여 이후에 커밋 다시 올리겠습니다.
> 아직 답을 풀지 못하여 이후에 커밋 다시 올리겠습니다.

Feat: 백준 휴게소 세우기

---

박정근/BOJ/Week25/[1461]도서관.java
박정근/BOJ/Week25/[1644]소수의_연속합.java
박정근/Programmers/Week25/타겟_넘버.java

> 그리디 + 정렬로 풀이했습니다.
> 책을 놓을 위치 중 가장 먼 곳을 고른 뒤, 그 먼 곳은 마지막에 M권만큼 가져가서 끝낸다고 생각하고 M개의 위치는 제외합니다. (오고 가면 거리가 2배가 되므로 가장 먼 곳은 한 번만 가는게 효율적입니다.)
> 가장 먼 곳을 제외한 나머지 위치들은 음수 / 양수 위치 따로, M권씩 옮깁니다. (M권씩 옮길 때 현재 가장 먼 곳 * 2 만큼의 거리를 이동합니다.)
> 에라토스테네스의 체 + 투 포인터로 풀이했습니다.
> 에라토스테네스의 체로 최대 4백만까지의 소수 리스트를 구한 뒤 연속한 소수 배열을 만듭니다.
> 연속한 소수 배열 안에서 투 포인터로 연속된 소수의 합이 n인 경우를, 찾기 위해 현재의 합을 증가시키거나 (right++) 감소시켜서 (left++) n을 만들 수 있는 경우의 수를 카운트합니다.
> 비트마스킹 + 완전 탐색으로 풀이했습니다.
> Week24 에서 풀었던 양궁대회와 비슷한 원리로 풀이할 수 있습니다.
> 주어지는 숫자의 개수는 최대 20개이므로, 0부터 2^20 까지 탐색하여, 비트 이론으로 i번째 비트가 0이면 i번째 수를 더하고, 1이면 i번째 수를 빼는 것으로 처리했습니다.

[25주차 / 박정근] 문제 풀이

---

이인복/BOJ/java/com/Week25/G3_1644/G3_1644.java
이인복/BOJ/java/com/Week25/G4_1461/G4_1461.java
이인복/BOJ/java/com/Week25/LV2_43165/LV2_43165.java

> 어떤 풀이가 최적인지는 모르겠으나 그리디 문제라고 생각이 되어서 `접근법`과 `구현`을  고민 했습니다. 
> 정렬을 필수라고 생각 되어서 정렬한 뒤 보니 움직임이 가장 적으려면 마지막 책을 처리한 뒤는 다시 돌아올 필요가 없더군요.
> 그래서 문제 풀이 들어가기전에 가장 먼 케이스는 미리 감산한 상태에서 시작 했습니다.(다시 돌아올 값 미리 감산 => 한 번 움직이면 왕복이니까 x2 만큼의 움직임이 필요)
>
> 1. 왼쪽(l) 과 오른쪽(r) 을 비교해 0 에서 가장 먼 방향을 선택
> 2. 해당 방향에서 한 번에 책을 들 수 있는 수(M) 만큼 책 제거
> 3. 음수와 양수가 한 조합에 섞인 경우는 계산을 조금 달리 했습니다.
> 문제에서 필요한 두 가지 방법을 다행히도 알고 있어서 풀 수 있었습니다. (`에라토스테네스의 체`, `투 포인터`)
> 400 백만번 제곱근을 이용한 소수를 구하면 시간 괜찮을 것 같기도 한데 어떨까요?
> 백트래킹 기법을 이용한 완전 탐색으로 모든 조합을 찾아서 타겟 넘버를 구했습니다.

[25주차 / 이인복 ] 문제 풀이

---

이성원/Backjoon/도서관.java
이성원/Programmers/타겟넘버.java

> dfs로 쉽게 풀 수 있었다. for 문을 사용해야 하나 했지만 for문을 사용안하고 가능했다
> 처음에 dp인줄 알 고 생각을 하다가 떠올르지 않아서 풀이를 참고하였다. 그리디 알고리즘을 사용하였고 정렬을 우선순위 큐로 정렬을 선행한 후에 계산해줬다. 그리디를 풀면서 느낀점은 해당 알고르즘을 몰라도 풀 수 있지 않을까..? 라는 생각이 들었다.
> {이번주는 빠듯해서 못풀었습니다 ㅠㅠ  }

✨ Week 25 이성원 문제풀이

---

양문규/Week25/도서관.py
양문규/Week25/소수의연속합.py

> 어려웠습니다. AI에게 아이디어 도움을 받아서 겨우 해결했네요. 감각이 중요한 듯 한데 아직은 문제를 보고 어떻게 풀어야할지 감이 잘 안옵니다. 연습을 많이 해야겠어요..
> 이건 지지난주에 투포인터 나온김에 추가적으로 연습하고자 선택한 문제였는데, 저는 갠적으로 좋은 연습이 되었습니다. 소수는 에라토스테네스의 체로 구하고 그걸 투포인터로 돌렸습니다. 하나 아쉬운 것은, 하나의 배열로 처리하지 못할 정도로 숫자가 크면 이걸 어떻게 나눌지는 연습이 필요할 것 같아요.
> 아쉽네요. 시간이 여의치 않아서 못 풀었습니다.

[25주차 / 양문규] 문제 풀이

---

강산아/boj/week25/소수의연속합.java
강산아/programmers/week24/양궁대회.java
강산아/programmers/week24/택배상자.java
강산아/programmers/week25/타겟넘버.java

> 이번 주는 최대한 혼자 힘으로 풀어보려 했습니다. 소수를 구하는 에라토스테네스 체 + 연속된 수를 구하는 투포인터 알고리즘을 사용하여 풀었습니다.
> dfs를 사용하여 풀어야 한다는 것을 알았지만 코드로서 적용을 못하여 도움을 받았습니다. 더 연습이 필요할 듯 합니다
> 시간 부족 + 문제 이해에 시간 소요가 많아 풀지 못하였습니다. 우선순위 큐를 이용하여 푸는 것 같은데.. 더 연습이 필요하겠습니다

Feat: 2024-11-23 백준 소수의 연속합

---

이인복/BOJ/java/com/Week26/G5_22862/G5_22862.java
이인복/BOJ/java/com/Week26/LV2_42586/LV2_42586.java
이인복/BOJ/java/com/Week26/LV2_72412/LV2_72412.java

> 시간 측정해서 풀었는데 저는 거의 3 시간 정도 풀이 했는데 이런 문제는 나오면 정말 절망적이겠네요...ㅎ
> 자료 구조를 잡고, 설계 하는데에만 시간 상당히 소모 했습니다.
> 주어지는 데이터 볼륨이 작지 않아서 검색을 어떻게 효율적으로 할 수 있도록 할 수 있을지 고민 많이 했습니다.
>
> 초기에는 트라이(Trie) 구조를 잡을 때 아무래도 CPP, Python, Java - Backend / Frontend 등 선택지가 정해져 있어서 하드 코딩과 유사하게 자료구조를 세팅하고자 했습니다.
```java
Map<String, Map<String, Map<String, Map<String, String>>>>
```
> 이런식으로 자료구조를 잡게 되면 변화에 대응하지 못하는 구조가 만들어져서 개인적으로 추구하는 형태는 아니여서 유현한 방법으로 구현 방식을 변경 하였고, 만들어 놓은 트라이 구조를 탐색하기 위해서 너비 우선 탐색(BFS) 를 사용해서 말단 노드까지 탐색 하도록 하였습니다.
>
> 쿼리로 인해 필터링된 결과로 말단 노드에 도착해서도 원하는 결과를 도출하기 위해서 이분 탐색(Binary Search)을 아용 하여서 시간 초과를 해결 했습니다.
>
> 개인적으로 문제를 풀면서 느낀점은 지금까지 꾸준히 했기 때문에 적재적소에 필요한 알고리즘을 사용할 수 있었다고 생각이 되네요.
> 트라이 알고리즘을 이용한 문제는 지금까지 알고리즘 스터디에서는 문제가 등장하지 않았지만 다행히도 알고 있는 구조라서 구현할 수 있었네요.
> 문제가 쉽지 않았어서 그림과 함께 블로그에 정리 하려고 하는데 정리가 된다면 …

[26주차 / 이인복 ] 문제 풀이

---

강산아/boj/week26/가장긴짝수연속한부분수열.java
강산아/programmers/week26/기능개발.java

> 큐를 활용한 구현 문제였습니다. (100-progresses[i]) % speeds[i] 이 0인지에 여부에 따라 큐에 값을 바로 넣거나, 혹은 +1 해서 넣어주고 넣은 값들을 하나씩 빼며 이전에 나온 값보다 큰지 비교 후 리스트에 cnt 변수를 add해 줍니다. 마지막으로 리스트 -> array로 변환 후 출력해 주었습니다. 
- [] <b>가장 긴 짝수 연속한 부분 수열 (large)</b>
>문제를 이해하는데 이틀이 걸렸습니다. '연속한 부분 수열'을 구하는 문제이기에 투 포인터 를 활용해주었는데 아직 문제를 다 못풀었습니다. 시간나는대로 마저 풀어서 다시 올리겠습니다.
> 난이도가 있어 풀지 못했습니다.

26주차 강산아 문제풀이

---

이상경/boj/LongestPartialSequence.java
이상경/programmers/FunctionDevelopment.java
이상경/programmers/RangkingSearch.java

> level 2여서 구현만 잘하면 되겠거니 했는데 정확도는 통과했는데 시간 효율성에서 문제가 발생했네요 ㅜ.ㅜ 그후에 길을 잃고 한번 찾아보다가 이분 탐색을 도입해야 한다는데 약간 감이 안잡혀서 추가로 확인해봐야 할 거 같습니다.
> 현재 기능 개발값의 남은 일감을 계산해서 그만큼 다른 기능개발에도 더해준다음 배열을 체크하면서 이미 100을 넘은 것들을 카운트해주면서 풀었습니다.
> 투포인터 사용해서 풀이했습니다!
resolve #153

[26주차 / 이상경] 문제 풀이

---

강산아/programmers/week27/메뉴리뉴얼.java
강산아/programmers/week27/퍼즐게임.java

> 이진 탐색을 이용해 풀었습니다.
> dfs의 숙련도가 떨어짐을 느꼈습니다. 열심히 공부해야 겠습니다.
> 풀이법이 떠오르지 않아 솔루션을 참고하니 크루스칼 알고리즘 문제이더군요. 공부해서 이해한다음 제출하겠습니다.

Feat: 2024-12-08 프로그래머스 퍼즐게임

---

이인복/BOJ/java/com/Week27/G3_10423/G3_10423.java
이인복/BOJ/java/com/Week27/LV2_340212/LV2_340212.java
이인복/BOJ/java/com/Week27/LV2_72411/LV2_72411.java

가능하면 모두 IDE 에서 풀이 하고 싶었는데, 진짜 인내심의 한계를 느낍니다..
디버깅 너무 불편하네요...ㅎ
> 자주 접했던 문제가 아니여서 어느정도 참고해서 풀었습니다.
> 아무래도 MST 개념에 조금 응용되서 발전기의 개수가 여러개이기 때문에 익숙하지 않은 알고리즘에 아주 약간의 응용이 들어가서
> 조금 더 가물가물 했던 것 같습니다.
> 
> 풀이의 핵심으로 Union & Find 와 PriorityQueue 를 이용 하여 최소 비용과 그래프 집합을 만들는 방법으로 풀이 하였습니다.
> 1. 주어진 문자열 정렬하기
>     - 조합을 만들 때 알파벳 순서로 조합 되도록 주어진 문자열을 우선 정렬 하였습니다.
>         - ex) XY(1개) 와 YX(1) => XY(2개) 같은 조합으로 카운팅 되도록 하였습니다.
> 2. 주어진 조건에 맞도록 필터를 걸어서 조건에 맞는 정렬된 문자열 리스트 생성
> 비교적 간단하게 풀이 하였습니다.
> 1. 이분 탐색을 통해서 후보 level 을 구하기
> 2. 주어진 `시간 계산법` 에 따라서 해당 level 이 limit 안에 수행될 수 있는지 확인 후 1, 2 순서 반복
> 3. 가장 최적의 해 반환

[27주차 / 이인복 ] 문제 풀이

---

이성원/Backjoon/퍼즐게임챌린지.java

> 퍼즐 게임 챌린지 같은 경우는 이분탐색으로 풀었습니다 ! 처음에 생각이 잘 안나서 계속 문제를 보다가 이분탐색인걸 깨닫고 문제를 풀었고 나중에 한번 더 풀어줘야곘다 생각했습니다
> 최종 발표가 다음주여서 코테에 집중을 못했네요 ㅠㅠ 발표끝나고 다시 집중력 있게 해서 실력좀 끌어올려야겠네요

feat: 퍼즐게임 챌린지 with Java

---

박정근/BOJ/Week28/[20040]사이클_게임.java
박정근/BOJ/Week28/[2251]물통.java
박정근/BOJ/Week28/[9663]N-Queen.java

이번 주는 일정이 많고 바빠서 일찍 풀이했습니다. 
> 너비 우선 탐색으로 풀이했습니다. 어떻게 하면 간결한 코드가 될 지 고민을 오래 했네요. (Solve Time : 0h 31m)
> 세 물통에 담겨 있는 물의 상태를 한 노드로 보고, 다른 물통으로 부으면서 상태가 달라질 때 이를 너비 우선 탐색할 수 있도록 큐를 사용했습니다.
> 유니온 파인드로 풀이했습니다. (Solve Time : 0h 9m)
> 저번 주 코드가 살짝 도움이 되었네요. 같은 그룹의 점을 이으려고 한다면 ans 를 처리합니다.
> find() 로 parent 배열을 동기화하고, union() 로 같은 그룹인지의 여부를 알 수 있습니다.
> 재귀와 비트마스킹으로 풀이했습니다. (Solve Time : 0h 11m)
> N-Queen 문제는 단순 재귀 구현으로 풀이해도 무방하지만, 비트 이론 (유사 흑마법)을 이용하면 1~2차원 배열을 사용하지 않아도 간단하게 구현할 수 있습니다.
> 주석에다 설명해보려 했지만 코드가 뚱뚱해질 것 같아서, 제가 예전에 정리해놓은 블로그 글을 보완해서 첨부하도록 하겠습니다. 지금 스킨 오류 때문인건지 블로그가 먹통이네요.

[28주차 / 박정근] 문제 풀이

---

이인복/BOJ/java/com/Week28/G4_20040/G4_20040.java
이인복/BOJ/java/com/Week28/G4_2251/G4_2251.java
이인복/BOJ/java/com/Week28/G4_9663/G4_9663.java

연말이라서 문제 풀기도 쉽지 않네요.
> 어떻게 풀어야 하는지 감이 안잡혀서 힘들었습니다.
> 사실 맨 처음에는 DP 문제인줄 알았으나 종료 시점을 알 수가 없어서 고민좀 했는데 BFS 문제 더군요.
> BFS 라고 해도 지금까지 풀었던 문제 보다는 조금 더 힘들었던 것 같습니다.
> 저번 주 Union & Find 문제 풀이하고 더 연습하고 싶어서 선정한 문제였는데
> 간단하게 풀리네요.
> visited 배열을 3개 만들어서 row, 양방향 대각선에 퀸이 있는지 확인하는 방법으로 풀이 했습니다.

[28주차 / 이인복 ] 문제 풀이

---

양문규/BOJ/Week28/9663.py

> 쉬울 줄 알고 선택했다가 엄청 헤매다가 겨우 풀었습니다. 다른 분의 유튜브 영상과 강의를 보면서 따라하는데도 한참 걸렸네요. 이번 주는 제가 고른 문제도 소화하느라 벅차서 겨우 해냈는데, 해냈다는 것에 의미를 두겠습니다. 백트래킹이 좀 어려워서, 다른 백트래킹 문제도 풀어보면서 실력을 올려야겠습니다. 
저는 처음에는 체스판의 모든 칸을 시작점으로 삼아서 (0, 0)에서 시작할 때, (0, 1)에서 시작할 때, ... 등으로 생각했었는데 이러다보니 중간에 방문 지점을 빼주는 작업에서 엄청 헤맸습니다. 참고한 코드는 훨씬 쉽게 풀고 있어서 많은 공부가 되었습니다.
참고 영상: https://www.youtube.com/watch?v=ltm-JX5R1pA

[28주차 / 양문규] 문제 풀이

---

강산아/boj/week27/NQueen.java
강산아/boj/week27/물통.java

> 혼자만의 힘으로 풀어보려 했습니다만, 정답을 보고 이해하는 방식으로 습득하였습니다. "A가 비었을때 C의 물 양"을 구하는 식이니 A,B,C, 각각 0보다 큰 경우 나머지 두 병에 물을 붓는 방식으로 탐색을 시도하였고, 이미 고려한 경우 탐색이 종료됩니다. 오름차순 정렬이니  A가 0인 배열에서 B가 큰 값부터 visited[0][B]가 true면 C에 있는 물의 양을 계산해서 출력합니다.
> 백트래킹 문제 풀이를 참고하여 풀었습니다.
> Union-find 방식을 잘 몰라 풀지 못하였습니다

Feat: Week 27 n-queen, 물통

---

이성원/Backjoon/N-Queen.java

> 백트래킹을 접해본지 너무 오래돼서 많이 해맸습니다.  규칙성을 찾으면 쉬운 문제지만 수학적인 사고가 많이 필요하다고 느꼈습니다.

[28주차 / 이성원] 문제 풀이

---

전유진/Programmers/귤고르기.java

[ 29주차 / 전유진 ] 문제풀이

---

이성원/Programmers/귤 고르기.java
이성원/Programmers/충돌위험 찾기.java

> {처음에 bfs로 접근을 하였고 그 이후 bfs를 안해도 풀 수 있겠다는 생각이 들어 모든 x,y축 가능 경로를 체크해주었고 문제의 핵심인 같은 시점에 충돌의 카운트를 해야했고 구글링을 한 후 힌트를 얻어 큐를 사용하여 같은 시점을 넣었습니다.}
> {간단하게 Map을 사용해서 풀었으나 배열을 사용해도 괜찮을 거 같았습니다.}

[29주차 / 이성원] 문제 풀이

---

강산아/boj/week27/물통.java
강산아/boj/week28/장난감조립.java
강산아/programmers/week28/귤고르기.java
강산아/programmers/week28/충돌위험찾기.java

> 위상 정렬 문제에 대한 경험이 없어 본 문제를 통해 원리를 보며 이해할 수 있었습니다. 좋은 문제였습니다.
> hash map 사용하여 중복 값 누적, reverse order로 내림차순 하여 풀었습니다. 
> 코드를 찾아 보았는데 이해가 안되어 아직 올리지 않았습니다. 이해하고 직접 적어보며 제출하도록 하겠습니다.

Feat: Week 28 장난감 조립, 귤 고르기

---

이인복/BOJ/java/com/Week29/G2_2637/G2_2637.java
이인복/BOJ/java/com/Week29/LV2_138476/LV2_138476.java

연말이라 일정이 많아서 몰아서 풀었고 한 문제는 풀이하지 못한채로 제출합니다. 😭
> 그룹핑과 정렬을 이용해서 간단하게 풀이 하였습니다.
> 위상 정렬 개념을 이용해서 풀이 하였습니다.
> 제가 위상 정렬 처음으로 접했을 때 풀이한 문제라서 기억이 새록새록 나네요.
> 탐색을 기본 부품에서 시작하는게 아닌 완성품 부터 기본 부품 방향으로 탐색 하면서 필요한 장난감을 누적 시켰습니다.
> 풀이하지 못했습니다..
> 쉬는 기간동안 풀이 해볼 예정입니다.

[29주차 / 이인복] 문제 풀이

---

박정근/BOJ/Week29/[2637]장난감_조립.java
박정근/Programmers/Week29/귤_고르기.java
박정근/Programmers/Week29/충돌위험_찾기.java

2024년 스터디 활동 고생 많으셨습니다! 이번 년도에 7주 동안 참여했었는데, Java로 문제 풀이하는 실력이 늘은 것 같아서 기분이 좋네요 :smile: 모두 한 해를 잘 마무리하셨으면 좋겠습니다!
> 완전 탐색으로 풀이했습니다. (Solve Time : 1h 8m)
> 지문대로 구현했습니다. 다른 사람들의 풀이를 보니 HashMap이나 Queue를 사용한 것 같은데, 로봇의 개수가 작아서 단순 반복문으로도 원활하게 돌아가네요.
> 그리디 정렬로 풀이했습니다. (Solve Time : 0h 5m)
> 귤 크기마다 개수를 센 뒤, 개수가 많은 귤 종류를 먼저 담으면 서로 다른 종류의 수가 최소가 됩니다.
> 위상 정렬에 다이나믹 프로그래밍 기법을 녹여 풀이했습니다. (Solve Time : 0h 30m)
> Y -> X 를 간선으로써 그래프를 모델링한 뒤, 위상 정렬하면 inDegree가 0인 부품들이 기본 부품이 됩니다.
> 부품 최대 개수가 적으니, 2차원 배열에 특정 부품을 만들기 위한 부품 개수를 기록한다면, 다음 부품을 만들고 싶다면 K번 곱해서 넣어주면 됩니다.

[29주차 / 박정근] 문제 풀이

---

박정근/BOJ/Week30/[21610]마법사_상어와_비바라기.java
박정근/Programmers/Week30/이중우선순위큐.java
박정근/Programmers/Week30/행렬_테두리_회전하기.java

> 완전 탐색으로 풀이했습니다. (Solve Time : 0h 12m)
> 지문대로 구현했습니다. 개인적으로 이런 문제를 풀 때, 배열을 회전 탐색하는 본인만의 방법을 손에 녹여두는 게 좋다고 생각합니다. 그만큼 좋은 문제인 것 같습니다!
> 완전 탐색 풀이에 큐를 녹여 구현했습니다. (Solve Time : 0h 35m)
> 지문대로 단순히 구현하는 문제입니다.
> 우선순위 큐로 풀이했습니다. NullPointerException 때문에 20분을 날렸네요.. (Solve Time : 0h 30m)
> 최솟값 우선순위 큐와 최댓값 우선순위 큐에 동시에 같은 값을 넣어서, 최솟값 / 최댓값을 자유롭게 뺄 수 있습니다.
> 최솟값 우선순위 큐에서 뺀 값이 최댓값 우선순위 큐에는 그대로 남아있다거나, 최댓값 우선순위 큐에서 뺀 값이 최솟값 우선순위 큐에는 그대로 남아있을 수 있습니다.
> -> 각각 삭제 큐를 추가로 두어서, 최솟값(최댓값) 을 빼기 전에 다른 큐에서 이미 뺀 값이라면 계속해서 지울 수 있도록 처리했습니다.
> 프로그래머스에서 다른 사람의 풀이를 보니 remove() 로 특정 순서? 값?을 지울 수도 있군요.
> 개인적인 의견이지만, 힙의 특성 상 peek 외에는 완전하게 정렬되어 있지 않기 때문에, 최댓값을 빼기 위해 최솟값 힙 트리를 탐색하면서 발견하고 지우는 코드보다는, 우선순위 큐를 더 사용해 동기화가 바로바로 되도록 하는 제 코드가 성능이 더 좋을겁니다. 
> 실제로 어느 코드 가져와서 돌려보니 적은 데이터에서는 다른 사람 코드가 더 유리하거나 비슷하지만, 큰 데이터에서는 제 코드가 …

[30주차 / 박정근] 문제 풀이

---

이인복/BOJ/java/com/Week30/G5_21610/G5_21610.java
이인복/BOJ/java/com/Week30/LV2_77485/LV2_77485.java
이인복/BOJ/java/com/Week30/LV3_42628/LV3_42628.java

평일에 고정으로 시간이 할애되는 일정이 생겨서 평일이 아닌 금, 토, 일 몰아서 문제 풀이 했습니다.
2월 까지는 평일에는 알고리즘 문제는 건들지 못할 것 같네요...ㅠ
> 기존 풀이는 Python 으로 풀이 하여서 Java 로 새롭게 풀이 했습니다.
> 요구사항을 풀이하기 위해서 필요했던 건 배열 좌표 이동과 Swap 인 것 같네요.
> 가벼운 구현 문제라 생각하고 출제 했는데 생각보다 까다로웠습니다.
> 좌표를 주요 `도메인`으로 생각하고 각 기능별로 쪼개서 볼 수 있도록 문제를 풀이 하였습니다.
> 코드 작성 후 한 번에 통과되긴 하는거 보니까 어려운 엣지 케이스는 없는 것 같은데 구현 자체가 오래 걸렸네요.
> 오름차순, 내림차순 두 개의 우선순위 큐를 이용하여 문제를 풀이 하였습니다.
> 매번 힙 정렬을 하는 개념으로 풀었는데 더 좋은 방법이 있을 것 같은 그런 느낌의 문제네요.

[30주차 / 이인복] 문제 풀이

---

이훈일/Baekjoon/마법사 상어와 비바라기.java
이훈일/Programmers/이중우선순위큐.java
이훈일/Programmers/행렬 테두리 회전하기.java

마지막 문제는 풀어봤던 문제였어서 리마인드만 했습니다. 2번 문제가 푸는데 상당히 오랜 시간을 사용했습니다. 조금 더 문제 푸는 시간을 단축해봐야겠습니다!
> 테두리를 모두 탐색하는 문제인 것 같습니다.
> 문제 푸는 시간은 1시간 정도 소요했습니다.
> 조건이 많아서 조건을 정리하면서 문제를 풀었다.
> 조건별로 함수로 나눠서 문제를 푸니깐 훨씬 정리가 잘되었습니다.
> 문제 푸는 시간은 총 2시간 정도 걸린 것 같습니다.
> 풀었던 문제라서 다시 리마인드만 했습니다.
> TreeSet으로 쉽게 풀었던 문제였습니다.

[30주차 / 이훈일] 문제 풀이 

---

이성원/Backjoon/마법사 상어와 비바라기.java
이성원/Programmers/이중우선순위큐.java
이성원/Programmers/행렬 테두리 회전하기.java

> {문제 이해는 쉬웠고, 중요한점은 첫  회전시 덮어진 값을 저장을 하여야 한다는것과, 순회시 반복문의 조건을 조금 달리 해줘야 합니다.
}
> {단순 구현이였고 시간을 좀 많이 썼습니다. 풀이법이 중간중간 떠오르지 않으면 구글링을 해서 참고해서 풀었습니다.
중요한 점은 if 조건을 까다롭게 설정해야 풀리는 거  같습니다.}
> {우선순위 큐 같은 경우 어떤 자료구조인지 모르고 구글링을 한 후 힙을 먼저 학습을 하였습니다. 자바의 컬렉션에는 이미 구현된 우선순위 큐가 있어서 최대힙을 기준으로 문제를 풀었고 최솟값 같은 경우 반복문을 돌려서 가장 작은 값을 삭제 시켜줬습니다.
하지만 다른 더 좋은 방안이 있을거 같습니다 굳이 최솟값을 삭제시킬때 마다 모든 힙을 다 도는게 아니라 최소힙을 하나 더 둬서 삭제 시켜주면 더 좋을 거 같다는 생각이 들었습니다. }

feat: 1월 2주차 코테 스터디

---

강산아/boj/week29/마법사상어와비바라기.java

** 금주는 처리해야 할 일이 많아 알고리즘에 시간을 많이 투자하지 못하였습니다. 반성합니다. 차주 내로 같이 올리겠습니다. **
> 프로그래머스 스러운 시뮬레이션 문제를 풀어봤습니다. 구현 문제 였으며 조건대로 구현하였습니다. 새로 배운 사실은 배열 크기를 벗어나는 위치를 잡는 부분에서 modulo 연산을 적용할 수 있다는 사실을 배웠습니다.
> 문제를 아직 보지 못하였습니다.
> 문제를 아직 보지 못하였습니다.

Feat: Week 29 강산아 문제풀이

---

이훈일/Baekjoon/인간 대포.java
이훈일/Baekjoon/치킨 배달.java
이훈일/Programmers/멀쩡한 사각형.java

> 다익스트라는 처음 풀어보는 유형이였고, 공부할 수 있는 좋은 기회였습니다
> 다익스트라 유형만 유튜브 영상으로 공부하고, 혼자서 풀어보았을 때 3시간 넘게 걸렸습니다.
> 이 [유튜브 영상](https://www.youtube.com/watch?v=QleeV_ipB7w)이 정리도 잘 되어 있고, 이해하기도 쉬워서 공유드립니다.
> 백트래킹 사용해서 해결했습니다.
> 문제 푸는데 사용 시간은 1시간 30분 정도 였습니다.
> 처음 풀었을 때에는 dp로 푸는 문제라고 생각해서 규칙을 찾았지만 규칙 찾기가 어려웠습니다.
> 그래서 결국 다른 사람의 풀이를 참고했는데, 처음 보는 유형의 문제여서 공유드립니다.
> 어떤 유형인지는 정확히 모르겠지만 그래프, 구현에 가깝다고 생각이 듭니다.
> [비슷한 유형의 문제](https://school.programmers.co.kr/learn/courses/30/lessons/181187) 하나 더 공유드립니다.

[31주차 / 이훈일] 문제풀이

---

이성원/Backjoon/치킨거리.java
이성원/Programmers/멀쩡한 사각형.java

> {조합 + 백트래킹을 사용해서 풀었습니다. 처음에 아이디어가 떠오르지 않아서 고민하다가 M개를 뽑아서 최솟값을 구하면 된다는 생각에 조합과 백트래킹을 사용하여 풀었습니디ㅏ}
> {멀쩡한 사각형 같은 경우는 패턴을 찾아야 하는 문제였습니다. 패턴만 찾으면 꽤나 쉽게 풀렸습니다}

feat: 1월 3주차 코테 스터디

---

박정근/BOJ/Week32/[1700]멀티탭_스케줄링.java
박정근/BOJ/Week32/[1780]종이의_개수.java
박정근/BOJ/Week32/[1926]그림.java

이번 주는 매우 바쁘네요.. 😢 마침 운이 좋게 문제가 잘 풀려서, 빠르게 pull request 올립니다.
> 분할 정복 재귀로 풀이했습니다. (Solve Time : 0h 13m)
> 한 종이가 같은 숫자로 이루어지지 않는다면, 9개 영역을 분할 (Divide) 하여 탐색하면 됩니다.
> 깊이 우선 탐색 혹은 너비 우선 탐색을 배울 수 있는 문제입니다. (Solve Time : 0h 9m)
> 가로 세로로 이웃한 1 영역을 탐색하면서, 가장 큰 1 영역의 크기도 구했습니다.
> 최적의 멀티탭 교체 알고리즘을 구현하는 문제입니다. (Solve Time : 0h 28m)
> 현재 멀티탭에 꽂혀있는 전기용품 중에서, 이후에 용품을 사용할 순서가 가장 마지막인 전기용품을 먼저 교체합니다.
> 페이지 교체 알고리즘 중 OPT 알고리즘에 대해 알고 있다면 해당 아이디어를 떠올리기 쉬워집니다.

[32주차 / 박정근] 문제 풀이

---

이인복/BOJ/java/com/year2025/Week32/G1_1700.java
이인복/BOJ/java/com/year2025/Week32/S1_1926.java
이인복/BOJ/java/com/year2025/Week32/S2_1780.java

> 그래프 탐색 문제 였기 때문에 BFS 채택해서 문제 풀이 하였습니다.
> 분할 정복 문제로 재귀 함수를 구현해서 문제 풀이 하였습니다.
> 이전에는 4 분면으로 나눠서 푸는 문제들만 풀었어서 그냥 4줄의 코드로 작성 했는데 이번에는 9개로 나눴기 때문에 어떻게 하면 코드 라인을 줄일 수 있을지 고민 하였습니다.
```java
// 이전 분할 정복 문제
solve(x, y);
solve(x, y + n);
solve(x + n, y);
solve(x + n, y + n);
// 이번에 구성한 분할 정복 메소드 호출
for(i) {
for(j) {
solve(x + n * i, y + n * j);
}
}
```
> 코드 한 줄 잘 못 넣어서 디버깅 하는데만 1시간 사용한 것 같네요...
> 한 줄의 코드가 전체 코드 덕분에 전체 로직이 틀어져서 어디서 문제 일으키는지 정말 오랫동안 찾았습니다....ㅠ
> 그리디 문제는 언제나 쉬워 보여서 쉽게 트라이하고, 항상 어려워서 낭패를 보는 거 같습니다.
> 그리디 문제는 역시 많이 풀어 보는게 정답 이겠죠?

[32주차 / 이인복] 문제풀이

---

이인복/BOJ/java/com/year2025/Week33/G2_1256.java
이인복/BOJ/java/com/year2025/Week33/G3_2473.java
이인복/BOJ/java/com/year2025/Week33/LV3_43105.java

평일에 2 문제 풀었는데 나머지 한 문제를 통과 못 했어서 늦게 올리네요 ㅠ..
> 점화식 도출 까지는 어렵지 않았던 것 같은데, 그 점화식을 이용해서 원하는 답을 찾는 과정까지가 저는 쉽지 않았아서
> 다를 분들의 문제 풀이를 참조 했습니다.
```
ex) N, M 이 2 2 라는 입력이 주워졌을 때
aazz
azaz
azza
zaaz
zaza
zzaa
위의 조합이 가능하고, a 로 시작 가능한 조합 3개, z 로 시작 가능한 조합이 3개 입니다.
ex) N, M 이 3 2 라는 입력이 주워졌을 때
aaazz
aazaz
aazza
azaza
azzaa
azaaz
zaaza
zaaaz
zazaa
zzaaa
- a 시작: 3 개
- aa 시작: 2개
- aaa 시작: 1개
- z 시작: 3개
- zz 시작: 1개
이렇게 누적된 값을 이용할 수 있기 때문에  aa 로 시작 하는 값은 a 로 시작 하는 값이 사전적으로 앞에 있기 때문에 기본적으로 3개의 조합은 aa 시작 보다 앞에 있습니다.
다른 예시로 z 로 시작 한다면 맨 앞 글자 a 로 시작하는 값들 6개가 기본적으로 사전적으로 앞에 있고 이는 코드 상에서는 아래 코드와 같이 a 로 시작하는 값 고려 해야합니다.
findStr(a, z - 1, k - startA);  // z 로 시작, k 에서 a 로 시작할 수 있는 경우 제거
```
> 저는 개인적으로 풀이를 참조 했어도 어려웠습니다..ㅠ
> DP 문제인 것은 바로 짐작하고 문제를 풀이 했습니다.
> 아쉬운점은 Bottom-Up 으로 하면 코드가 정말 간결하고, 신경 쓸 포인트가 많이 있지 않아는데 …

[33주차 / 이인복] 문제풀이

---

박정근/BOJ/Week33/[1256]사전.java
박정근/BOJ/Week33/[2473]세_용액.java
박정근/Programmers/Week33/정수_삼각형.java

> DP로 풀이했습니다. (Solve Time : 0h 06m)
> 간단한 점화식의 DP 문제입니다. 삼각형 형태를 2차원 배열로 표현하는 것이 포인트입니다.
> 조합론 원리를 이용해 구현 및 풀이했습니다. (Solve Time : 1h 31m)
먼저, a와 z 를 이용해 만들 수 있는 문자열을 사전 순으로 나열해봤습니다.
> - 원활한 설명을 위해, a가 N개 있는 문자열 안에 z를 M개 넣는다고 가정합니다. 
> - 이때 z의 위치는 맨 뒤 삽입 가능 공간부터 0입니다.
Ex. (N, M) = (3, 3)
|순서|z의 위치|문자열|
|---|---|---|
|1|0 0 0|aaazzz|
|2|1 0 0|aazazz|
|3|1 1 0|aazzaz|
|4|1 1 1|aazzza|
|5|2 0 0|azaazz|
|6|2 1 0|azazaz|
|7|2 1 1|azazza|
|8|2 2 0|azzaaz|
|9|2 2 1|azzaza|
|10|2 2 2|azzzaa|
|11|3 0 0|zaaazz|
|12|3 1 0|zaazaz|
|13|3 1 1|zaazza|
|14|3 2 0|zazaaz|
|15|3 2 1|zazaza|
|16|3 2 2|zazzaa|
|17|3 3 0|zzaaaz|
|18|3 3 1|zzaaza|
|19|3 3 2|zzazaa|
|20|3 3 3|zzzaaa|
> (N, M) = (3, 3) 일 때, 찾은 규칙성은 다음과 같습니다. 
> - 첫 번째 z의 위치가 바뀌기 위해선 각각 1, 3, 6, 10... 개의 문자열을 지나야 합니다.
> - 두 번째 z의 위치가 바뀌기 위해선 각각 1, …

[33주차 / 박정근] 문제 풀이

---

이훈일/Baekjoon/사전.java
이훈일/Baekjoon/세 용액.java
이훈일/Programmers/정수 삼각형.java

> 일단 유형을 보면 DP로 해결하는 문제입니다.
> 2번 째 층부터 시작해서 전 층에 영향을 받은 노드 중 가장 큰 값을 현재 노드에 더하면서 마지막 층까지 수행합니다.
> 그리고, 마지막 층 중에서 가장 큰 값을 찾았습니다.
> 문제 풀이 소요 시간은 1시간 정도 걸렸습니다.
> 유형조차 예상할 수 없어서, 다른 사람의 풀이를 보고 해결했습니다.
> 이 문제의 유형도 DP로 풀었습니다.
> 점화식 = NCm = N-1Cm + N-1Cm-1 입니다. 이 점화식을 모르면 절대 못풀었을 문제인 것 같습니다. 이 점화식을 이용해서 먼저 NCm의 모든 경우의 수를 먼저 저장해놓습니다.
> 문제 풀이 소요 시간은 3시간 정도 걸렸습니다. 
> 처음에는 백트래킹인가..?? 했는데 시간 복잡도가 터진다.
> 그래서 다른 방법을 생각해 보다가, 여러워서 다른 사람의 풀이를 보고 풀었음.
> 유형은 투포인터입니다.
> 1개의 포인터는 for문으로 N-3 까지 돌고, 2개의 포인터를 이용해서 가장 0과 가까운 수를 찾았습니다.
> 시간복잡도는 N^2인 것 같습니다.
> 문제 풀이 소요 시간은 3시간 정도 걸렸습니다.

[33주차 / 이훈일] 문제 풀이

---

이다예/baekjoon/Week33/1256.java
이다예/baekjoon/Week33/2473.java
이다예/baekjoon/Week33/정수삼각형.java

> ### 풀이:
> 
>  정수 삼각형의 맨 밑단부터 한줄 씩 위로 올라가며 갱신하는 방식으로 누적합으로 구했습니다. 
> x-1번째 줄에 인덱스 0칸의 경우, x줄의 인덱스 0칸과 1칸을 합했을 때 나올 수 있는 값 중 큰 값으로 갱신했습니다. 
> 
> ### 느낀점:
> 
>  문제를 고정된 시각이 아닌 다양한 각도로 바라보고 풀이 방법을 고민해보는 것이 향후 다른 문제를 풀때도 큰 도움이 될 것 같습니다.  
> ### 풀이: 
> 
>  점화식을 스스로 세울 수 없어서 인터넷에 있는 다른 코드를 참고하여 작성후 완벽 이해하는 과정을 거쳤습니다. 주석을 통해 상황에 맞는 세세한 풀이를 작성해두었습니다. 
>  
>  1. dp 배열의 자료형을 double로 사용한 이유
> 
> - 조합의 개수는 매우 빠르게 증가하며, 최대 10^29(100경) 이상이 될 수 있음
> - int(약 21억)와 long(약 9경)보다 더 큰 값을 저장하기 위해 double 사용함
> - double은 실수형이지만, 정확한 값이 아닌 "10억보다 크냐?"만 판단하면 되므로 문제없음
> - BigInteger도 사용 가능하지만, 객체 기반이므로 연산 속도가 느려 부적합함
> 
> 2. StringBuilder를 전역으로 선언한 이유
> 
> - 하나의 객체를 재사용하여 성능 최적화를 하기 위함
> - String을 사용할 경우, 문자열 수정 시 새 객체가 생성되어 성능 저하가 발생함
> - StringBuilder는 기존 객체를 수정하는 방식이므로 메모리 절약이 가능함 
> 
> 3. check(a, z) 함수 (조합 …

[33주차 / 이다예] 문제풀이

---

이성원/Backjoon/세 용액.java
이성원/정수 삼각형.java

> {DP로 해결하였고 삼각형이 다음 행으로 내려가는 규칙만 찾으면 쉬운 문제였습니다.
저는 가장 자리는 일정하게 더 해줬고 가운데 자리만 전 행과 비교하여 값을 구해나갔습니다.}
> {조합 백트래킹인가 하고 풀었지만 3중 for문이 나와 제약사항을 확인하고 넣어본 결과 시간 복잡도에서 터지겠구나 판단하여 
투포인터를 사용하여 시간복잡도를 줄여서 풀었습니다.}

Week33 이성원 문제풀이

---

이훈일/Baekjoon/보석 도둑.java
이훈일/Baekjoon/여행 가자.java
이훈일/Programmers/[3차] n진수 게임.java

> 모든 보석을 무게로 정렬하여 우선순위큐에 넣어서 문제를 풀었습니다.
> 가치의 총 합을 sum으로 두었는데, long이 아닌 int로 해서 이 오류 찾는데 오래 걸렸습니다.
> 총 소요 시간은 2시간 걸렸습니다.
> 진수 변환하는 함수를 까먹고 있었는데, 다시 리마인드할 수 있었던 문제였습니다.
> 총 소요 시간은 1시간 걸렸습니다.
> 그래프 문제로 해결했습니다.
> 잘은 모르지만 이런 문제가 유니온 파인드 유형인가..?? 생각했습니다.
> 총 소요 시간은 1시간 걸렸습니다.

[34주차 / 이훈일] 문제풀이

---

이성원/Programmers/n진수게임.java
이성원/Programmers/보석도둑.java

> {우선순위  큐로 풀었지만 로직은 맞는거 같은데 답이 틀려서 혹시 어떤 부분이 문제인지 코드리뷰 부탁드립니다.}
> {구현으로 문제를 풀었고 30분 걸렸습니다. }

[34주차 / 이성원] 문제풀이

---

이훈일/Programmers/비밀 코드 해독.java
이훈일/Programmers/서버 증설 횟수.java
이훈일/Programmers/입국심사.java

> 문제 유형은 구현 문제 같았습니다.
> players = 24, m = 1000이 최대인 것을 봤을 때 시간복잡도를 크게 생각 안해도 괜찮겠다 생각했습니다.
> HashMap을 사용해서 key로 player의 index, value로 서버 증설 횟수를 넣어서 해결했습니다.
> 문제 소요 시간은 1시간 정도 소요했습니다. 
> 문제 유형은 완탐 문제 같았습니다.
> 얘도 시간복잡도를 크게 생각 안 했습니다.
> 5개의 비밀코드를 1부터 N까지 조합하면서 맞는 비밀코드인지 확인했습니다.
> 저는 매개변수 배열을 전역변수 배열로 바꿀 때 하나씩 일일히 넣어줬는데 다른 좋은 방법이 있으신 분은 알려주세요.
> 문제 소요 시간은 1시간 반 정도 소요했습니다.
> 문제 유형은 이분탐색 입니다.
> 처음 해결할 때에는 DP인가? 했는데 결국 다른 사람의 풀이를 보니깐 이분탐색으로 해결하는 거더라고요.
> 시간복잡도가 꽤 빡세게 잡혀있습니다.
> 자세한 설명은 스터디 진행할 때 하겠습니다.
> 문제 소요 시간은 3시간 정도 소요했습니다.

[35주차 / 이훈일] 문제풀이

---

강산아/programmers/week35/서버증설횟수.java
강산아/programmers/week35/입국심사.java

> 처음에 큐로 풀었다가 헷갈려서 다시 배열로 풀었습니다.
> 처음에 감을 못 잡고 해설을 본 후에 이분 탐색을 이용해 풀이했습니다.
>

Feat: Week 35 강산아 문제풀이

---

이인복/BOJ/java/com/year2025/Week35/LV2_388352.java
이인복/BOJ/java/com/year2025/Week35/LV3_43238.java
이인복/BOJ/java/com/year2025/Week36/G3_1238.java
이인복/BOJ/java/com/year2025/Week36/G4_1647.java
이인복/BOJ/java/com/year2025/Week36/G5_5557.java

> 초기에 DP 로 접근하지 않아서 `OOM` 까지 만나 버렸네요 ㅎㅎ... (2^63) 엑사 바이트 단위를 보고 생각 했어야 했는데, 뇌 빼고 해버렸습니다.
> 콘솔로 만들 수 있는 수를 전부 찍어보니 중복되는 숫자가 엄청 많은걸 알아서 카운팅 하는 방식 이라는 것을 알았습니다.
```
for(int i = 0; i < N - 2; i++) 
for(int j = 0; j < 21; j++) 
```
> i 는 몇 번째 연산인지, j 는 값의 최대 값이 20이기 때문에 각 연산 결과를 결과에 맞는 인덱스 요소에 증감 시키는 방식으로 카운팅(메모이제이션) > 하였습니다.
> 문제를 읽자마자 MST 문제라는 생각이 들었습니다.
> 그래프를 구성할 때 2 차원 배열로 구성 했었는데 `메모리 초과` 가 발생 했었는데, 아무래도 간선이 안주어지는 버려지는 공간이 많아서 였었던 
> 것 같습니다.
> 그래서 연결된 노드들은 '리스트'로 변경 하였더니 통과 했습니다.
> 문제의 읽고, 풀이가 명확하게 떠올라서 코드는 쉽게 작성 했습니다.
> `다익스트라` 알고리즘을 이용해서 노드간 최소 거리를 계산 했고, 되돌아가는 거리는 별도로 알고리즘을 호출해서 한 번 더 돌렸습니다.
> `메모리 초과` 몇 번 겪었는데, 배열을 재활용 하도록 하고, class 에 Comparable 을 구현 했었었는데, 지우니까 통과 했습니다. (이건 이유 잘 모르겠음)

[36주차 / 이인복] 문제풀이

---

정준상/BOJ/1학년.java
정준상/BOJ/도시 분할 계획.java
정준상/BOJ/파티.java

> 중간에 나오는 수가 반드시 `0 <= ? <= 20` 임을 이용해 DP 방식으로 풀이하였습니다.
> `cntTable[i][j]` 는 `i + 1` 번째 수까지 사용했을 때, 수 `[j]` 가 만들어질 수 있는 경우의 수입니다.
> 때문에 `cntTable[0][ 처음 주어진 수 ] = 1 (prev)` 로 초기화하고, `cntTable[1][ 처음 - (2 번째 수) ] += prev`, `cntTable[1][ 처음 + (2 번째 수) ] += prev` 하며 문제를 풀이할 수 있습니다.
---
> 해당 문제를 보고 MST 로 풀이할 수 있겠다 생각하였습니다.
> 전체 마을을 한 MST 로 묶은 다음, `MST 간선 중 가장 비용이 높은 간선` 을 제거하면 문제의 답이 되리라 생각했습니다.
> 문제의 간선 `(M)` 이 최대 `1,000,000` 이라 나와있어 `크루스칼 알고리즘` 으로 MST 를 구현했습니다.
---
> 문제를 보고 `다익스트라 알고리즘` 으로 해결할 수 있겠다 생각했습니다.
> 하지만 풀고 보니 `1700 ms` 정도가 나와 다른 분들의 코드를 참조해 최적화했습니다.
> `다른 node --> X` 로의 최단 거리들을 `간선 방향을 역전` 시켜 `단 한번` 에 알아낼수 있음을 활용했습니다.
> 좋은 insight 를 주는 문제였던 것 같습니다.
---
|                |       1학년 |  도시 분할 계획   |     파티      |
|:--------------:|:---------------------:|:-----------:|:-------------:| …

[36주차 / 정준상] 문제풀이

---

박정근/BOJ/Week36/[1238]파티.java
박정근/BOJ/Week36/[1647]도시_분할_계획.java
박정근/BOJ/Week36/[5557]1학년.java

> DP로 풀이했습니다. (Solve Time : 0h 20m)
> 덧셈과 뺄셈을 수행하는 모든 경우를 탐색하려고 하면 시간 초과가 발생합니다. DP로 경우의 수를 빠르게 구했습니다.
> dp[i][j] : i번째 수까지 계산했을 때 수 j가 결과로 나오는 경우의 수
> `dp[i][j] = dp[i-1][j - arr[i]] (단, j - arr[i] >= 0) + dp[i-1][j + arr[i]] (단, j + arr[i] <= 20)`
> 최소 스패닝 트리로 풀이했습니다. (Solve Time : 0h 15m)
> 유지비가 작은 간선부터 최소 스패닝 트리를 구축한 뒤, 사용한 간선 중 가장 유지비가 많이 드는 간선 하나를 제외해서 두 마을로 분리하면 됩니다.
> 스패닝 트리를 구한 뒤, 가장 비용이 큰 간선을 찾아 전체 비용에서 뺍니다.
> 다익스트라로 풀이했습니다. (Solve Time : 0h 23m)
> 각각 학생마다, (학생 마을부터 X 마을까지 거리) + (X 마을부터 학생 마을까지 거리) 를 구해 최댓값을 찾습니다.
> 정방향 다익스트라 + 역방향 다익스트라를 통해 구현했습니다.
> 어떻게든 구현을 해보긴 했는데, 코드가 좀 리팩토링이 필요한 것 같아서... 어떻게 하면 더 가독성 있게 보일지 고민하다가 제출한 문제입니다. 조언 구합니다 😭

[36주차 / 박정근] 문제 풀이

---

박정근/BOJ/Week38/[1600]말이_되고픈_원숭이.java
박정근/BOJ/Week38/[7579]앱.java
박정근/Programmers/Week38/배달.java

> Knapsack DP로 풀이했습니다. (Solve Time : 0h 19m) (136ms / 18600KB)
> 비용을 c만큼 사용해서 앱들을 비활성화 했을 때 얻을 수 있는 메모리의 최대 바이트를 구해, M 이상이 되면 C를 출력하는 코드입니다.
> 플로이드 워셜로 풀이했습니다. (Solve Time : 0h 17m) (6.97ms / 96MB)
> 그래프 안에서 1번 마을부터 다른 마을까지의 최단 거리를 구하는 문제입니다.
> 정점의 개수가 적으므로 플로이드 워셜 풀이가 가능합니다.
> 두 마을 a, b를 연결하는 도로는 여러 개가 있을 수 있습니다. -> 이를 주의하면 쉽게 정답을 맞을 수 있는 문제입니다.
> BFS로 풀이했습니다. (Solve Time : 0h 14m) (604ms / 87504KB)
> BFS 로 탐색하여 (y, x) 까지 가는 최소 이동 횟수를 구하면서, 나이트로 몇 번 이동했는지의 횟수도 방문 처리 기준에 포함해야 합니다.
> 왜냐하면, 초반에 나이트 이동 횟수를 다 소모해 단순히 h x w 방문 처리를 하게 되었을 때, 목적지까지 가지 못하고 이동 횟수를 전부 소모한다면, 나중에 인접 이동으로 돌아와서 (나이트 이동 횟수를 소모하지 않은 상태) 나이트 이동을 했을 때 이미 방문 처리 된 곳이라 정답을 발견하지 못할 수 있습니다.
> 따라서, 나이트 이동 횟수마다 방문 처리를 다르게 함으로써, 나이트 이동을 어떻게-얼마나 사용했는지에 따라 다르게 경로를 찾을 수 있어야 합니다.

[38주차 / 박정근] 문제 풀이

---

정준상/BOJ/2025/03/말이 되고픈 원숭이.java
정준상/BOJ/2025/03/앱.java
정준상/Programmers/2025/03/배달.java

> 풀이하지 못해 [해답](https://cocoon1787.tistory.com/319) 을 참고하였습니다.
> 공부하는 기분으로 DP 배열을 1 차원으로 축소시켜 재풀이 하였습니다.
---
> 다익스트라를 이용해 풀이하였습니다.
---
> 방문 여부를 `2 차원 배열` 에서 `3 차원 배열` 로 확장하면 바로 풀리는 BFS 문제입니다.
> 코드를 더 깔끔하게 만들고 싶은데... 잘 모르겠네요 조언 구합니다 😢
---
|                |       앱  |  배달  |     말이 되고픈 원숭이      |
|:--------------:|:---------------------:|:-----------:|:-------------:|
|    **Runtime**     |        156 ms        |  8.03 ms  |   456 ms    |
|     **Memory**     |        16.384 MB        |   93.8 MB    |    89.672 MB     |
| **Used algorithm** |  Dynamic programming  | Shortest path (Dijkstra)  | BFS |

[38주차 / 정준상] 문제풀이

---

이인복/BOJ/java/com/year2025/Week38/G3_7579.java
이인복/BOJ/java/com/year2025/Week39/G2_12015.java

1 풀이, 1 풀이중, 1 문제도 못 읽음 으로 이번 주 마무리 합니다.
> 배열로 풀이하는 문제인줄 알았고 문제 선정 했었는데.. 퓰지 못해서 다른 사람 풀이를 참조 해보니
> 이분 탐색을 같이 사용하는 문제였네요.
> 저에게는 난이도가 조금 있었던 문제였습니다.
> 현재 풀이 중인데 생각처럼 안풀리네요.. ㅎ
> 풀이 x

[39주차 / 이인복] 문제풀이
